if( WIN32 )
  set( ENV{PATH} "$ENV{PATH};${CMAKE_CURRENT_BINARY_DIR}")
  execute_process(
          COMMAND ${TEXTGEN_EXE}
          WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
  )
else()
  set( ENV{LD_LIBRARY_PATH} "$ENV{LD_LIBRARY_PATH}:${CMAKE_CURRENT_BINARY_DIR}")

  execute_process(
          COMMAND ./${TEXTGEN_EXE}
          WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
  )
endif()




